version: '3.1'

services:
  proxy:
    build: .
    ports:
      - "8000:8000"
      - "8080:8080"

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example